SnakesNames = {
    1: "Naja",
    2: "Sucuri",
    3: "Cascavel",
    4: "Mamba-Negra",
    5: "Jararaca",
    6: "Jiboia",
    7: "Coral-Verdadeira",
    8: "Coral-Falsa",
    9: "Píton",
    10: "Urutu-Cruzeiro",
    11: "Surucucu (ou Pico-de-Jaca)",
    12: "Taipan",
    13: "Cobra-Cega",
    14: "Cobra-Cuspideira",
    15: "Víbora-de-Chifres",
    16: "Cobra-do-Mar",
    17: "Cobra-Rei",
    18: "Cobra-Marrom",
    19: "Caninana",
    20: "Cobra-D'água",
    # Preencher o resto
    43: "Ekans",
    44: "Arbok",
    45: "Nagini",
    46: "Serpente do Éden",
    47: "Medusa",
    48: "Basilisco",
    49: "Orochimaru",
    50: "Jormungand",
    51: "MissingNo."
}